= Environment setup
:suborder: 3

Once a Google project and of the key cluster infrastructure and backend services are set up, it's time to add a specific deployment environment.

=== Storage

Create the Google Storage buckets for each environment.

WARNING: Bucket names have to be globally unique, which poses problems working with different environments: the service(s) using the Storage backend will need to be configured to use the appropriate buckets.

=== Postgresql

The setup folder has the DDL to set up the Pentaho logs database in a database of choice.

=== VPC network

Under "External IP addresses", reserve a global static IP address to be used by the ingress later on.
Give it a name like `stage-ip4-dataworkbench-io`:

[source,bash]
----
gcloud compute addresses create stage-ip4-dataworkbench-io --global
----

Make sure to use the `--global` flag, otherwise the ingress will not bind to it.

The address can now be used in the Ingress specification:

[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dwb-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stage-ip4-dataworkbench-io
----

Once the IP address is available, add it to the DNS of the domain of choice.

=== Namespaces

The respective testing, staging and production branches specify their namespace via kustomize.

In `namespace.yaml`:

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: testing
----

In `kustomize.yaml`:

[source,yaml]
----
# ...
resources:
- namespace.yaml

namespace: testing
----

[WARNING]
====
Nodes and persistentVolumes are not in a namespace.
For storage in persistentVolumes, this requires some additional configuration to make sure applications don't interfere across namespaces.
====

=== MongoDB

Once the Mongo service is up and running, it still needs to be configured with the database for the deployment.

Once the collections within the database are created, it is good practice to create indexes on the appropriate fields, to speed up retrieval and prevent warnings from Mongo.
