apiVersion: batch/v1
kind: Job
metadata:
  name: iati-remove-obsolete-data-oneoff
  labels:
    env: develop
    tier: backend
    focus: sync
spec:
  template:
    spec:
      nodeSelector:
        focus: application
      containers:
      - name: iati-kitchen
        image: gcr.io/dataworkbench-io/iati-kitchen:0.3.17
        args:
          - "-file=remove_obsolete_data.kjb"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /home/workspace
          name: workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        hostPath:
          path: /home/workspace
          type: DirectoryOrCreate
