apiVersion: batch/v1
kind: Job
metadata:
  name: iati-data-refresher-job
spec:
  template:
    spec:
      containers:
      - name: iati-data-refresher-job
        image: gcr.io/dataworkbench-io/iati-data-refresher:0.10.2-deploy
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: iati-data-refresher-config-269cd9889g
        command:
          - "/bin/sleep"
          - "2h"
        volumeMounts:
        - mountPath: /home/snapshot
          name: iati-snapshot
        - mountPath: /home/urls
          name: iati-urls
        - mountPath: /home/workspace
          name: workspace
        ports:
        - name: webhook-server
          containerPort: 9000
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Gi"
      restartPolicy: Never
      volumes:
      - name: iati-snapshot
        hostPath:
          path: /home/snapshot
          type: DirectoryOrCreate
      - name: iati-urls
        hostPath:
          path: /home/urls
          type: DirectoryOrCreate
      - name: workspace
        hostPath:
          path: /home/workspace
          type: DirectoryOrCreate
