apiVersion: batch/v1
kind: Job
metadata:
  name: iati-remove-obsolete-data-oneoff
  labels:
    env: develop
    tier: backend
    focus: sync
spec:
  template:
    spec:
      nodeSelector:
        focus: validation
      containers:
      - name: iati-kitchen
        image: gcr.io/dataworkbench-io/iati-kitchen:0.3.5
        args:
          - "-file=remove_obsolete_data.kjb"
          - "-level=Detailed"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
      restartPolicy: Never
