apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iati-data-validator-box
  labels:
    app: iati-data-validator-box
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iati-data-validator-box
        tier: backend
    spec:
      containers:
      - name: iati-data-validator-box
        image: gcr.io/dataworkbench-io/iati-data-validator:0.9.18-loop4
        imagePullPolicy: Always
        ports:
        - name: webhook-server
          containerPort: 9000
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Gi"
        env:
          - name: PROJECT_ID
            value: dataworkbench-io
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      volumes:
      - name: workspace
        emptyDir: {}