apiVersion: batch/v1
kind: Job
metadata:
  name: iati-kitchen-job
spec:
  template:
    spec:
      containers:
      - name: iati-kitchen
        image: gcr.io/d4d-dataworkbench/iati-kitchen:0.10.1
        command:
          - "/bin/sleep"
          - "2h"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /home/workspace
          name: workspace
        - name: kettle-properties-volume
          mountPath: /home/.kettle/kettle.properties
          subPath: kettle.properties
      restartPolicy: Never
      volumes:
      - name: workspace
        hostPath:
          path: /home/workspace
          type: DirectoryOrCreate
      - name: kettle-properties-volume
        configMap:
          name: iati-kitchen-kettle-properties-hcb5mgfcd5
