apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataworkbench-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: your-static-ip-name
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: web-certificate
spec:
  domains:
    - stage.example.com