apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ingress-ip-name.yaml
- scaling-patches.yaml
- scheduling.yaml

resources:
- namespace.yaml
- scaling-hpa.yaml

namespace: default

configMapGenerator:
- name: homepage-config
  files:
  - env/project.env

configMapGenerator:
- name: iati-data-validator-config
  files:
  - env/project.env
  - env/iati-data-validator.env

configMapGenerator:
- name: iati-data-refresher-config
  files:
  - env/project.env
  - env/iati-data-refresher.env
  
configMapGenerator:
- name: iati-kitchen-config
  files:
  - env/project.env
  - env/iati-kitchen.env

configMapGenerator:
- name: validator-api-public-config
  files:
  - env/project.env

configMapGenerator:
- name: validator-api-config
  files:
  - env/project.env

configMapGenerator:
- name: validator-front-end-config
  files:
  - env/project.env
