apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ingress-config.yaml
- scaling-patches.yaml
- scheduling.yaml

resources:
- namespace.yaml
- scaling-hpa.yaml

namespace: default

images:
- name: gcr.io/d4d-dataworkbench/homepage
  newTag: 0.3.6
  
- name: gcr.io/d4d-dataworkbench/validator-api
  newTag: 1.2.0-alpha
  
- name: gcr.io/d4d-dataworkbench/validator-front-end
  newTag: 0.10.0-staging
  
- name: gcr.io/d4d-dataworkbench/iati-data-validator
  newTag: 0.12.9
  
- name: gcr.io/d4d-dataworkbench/iati-kitchen
  newTag: 0.10.0
  
- name: gcr.io/d4d-dataworkbench/iati-data-refresher
  newTag: 0.10.2-deploy

configMapGenerator:
- name: homepage-config
  env: env/project.env

- name: iati-data-validator-config
  env: env/iati-data-validator.env

- name: iati-data-refresher-config
  env: env/iati-data-refresher.env
  
- name: iati-kitchen-config
  env: env/iati-kitchen.env

- name: iati-kitchen-kettle-properties
  files:
  - properties/kettle.properties

- name: validator-api-public-config
  env: env/api.env

- name: validator-api-config
  env: env/api.env

- name: validator-front-end-config
  env: env/project.env

- name: frontend-env-js
  files:
  - properties/env.js

- name: api-datasources-properties
  files:
  - properties/datasources.local.json

- name: msmtp-config
  files:
  - properties/msmtprc

- name: gitcookies
  files:
  - properties/gitcookies