apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ingress-ip-name.yaml
- scaling-patches.yaml
- scheduling.yaml

resources:
- namespace.yaml
- scaling-hpa.yaml

namespace: default

configMapGenerator:
- name: homepage-config
  env: env/project.env

- name: iati-data-validator-config
  env: env/iati-data-validator.env

- name: iati-data-refresher-config
  env: env/iati-data-refresher.env
  
- name: iati-kitchen-config
  env: env/iati-kitchen.env

- name: iati-kitchen-kettle-properties
  files:
  - properties/kettle.properties

- name: validator-api-public-config
  env: env/api.env

- name: validator-api-config
  env: env/api.env

- name: validator-front-end-config
  env: env/project.env

- name: frontend-env-js
  files:
  - properties/env.js