apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ingress-config.yaml
- scaling-patches.yaml
- scheduling.yaml
- front-end.yaml

resources:
- namespace.yaml
- scaling-hpa.yaml

namespace: default

images:
- name: gcr.io/d4d-dataworkbench/validator-api
  newTag: 1.2.0-alpha

- name: gcr.io/d4d-dataworkbench/validator-front-end
  newTag: 0.10.0-staging

- name: gcr.io/d4d-dataworkbench/iati-data-validator
  newTag: 0.12.9

- name: gcr.io/d4d-dataworkbench/iati-kitchen
  newTag: 0.10.0

configMapGenerator:
- name: iati-data-validator-config
  env: env/iati-data-validator.env

- name: iati-kitchen-config
  env: env/iati-kitchen.env

- name: iati-kitchen-kettle-properties
  files:
  - properties/kettle.properties

- name: validator-api-public-config
  env: env/api.env

- name: validator-api-config
  env: env/api.env

- name: validator-front-end-config
  env: env/project.env

- name: frontend-env-js
  files:
  - properties/env.js

- name: api-datasources-properties
  files:
  - properties/datasources.local.json

- name: ssmtp-config
  files:
  - properties/ssmtp.conf
