apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ingress-ip-name.yaml
- scaling-patches.yaml
- scheduling.yaml

resources:
- namespace.yaml
- scaling-hpa.yaml

namespace: default