apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api-public
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-front-end
spec:
  replicas: 3
