apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-api-public
spec:
  replicas: 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-api
spec:
  replicas: 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validator-front-end
spec:
  replicas: 1
