apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-remove-obsolete-data
spec:
  schedule: "23 3 * * *"
---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: iati-remove-orphan-data
# spec:
#   schedule: "53 3 * * *"
# ---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-refresh-from-registry
spec:
  schedule: "30 7 * * *"
