apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-data-validator
  labels:
    env: develop
    tier: backend
    focus: validation
spec:
  schedule: "7/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            focus: validation
          containers:
          - name: iati-data-validator-rules
            image: gcr.io/dataworkbench-io/iati-data-validator:0.2.0
            args:
              - rules
            volumeMounts:
            - mountPath: /workspace
              name: workspace
            resources:
              requests:
                memory: "1Gi"
                cpu: "700m"
              limits:
                memory: "3Gi"
          restartPolicy: OnFailure
          volumes:
          - name: workspace
            hostPath:
              path: /home/workspace
              type: DirectoryOrCreate
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-data-validator-big
  labels:
    env: develop
    tier: backend
    focus: validation
spec:
  schedule: "23,53 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            focus: validation
          containers:
          - name: iati-data-validator-rules-big
            image: gcr.io/dataworkbench-io/iati-data-validator:0.2.0
            args:
              - rules-big
            volumeMounts:
            - mountPath: /workspace
              name: workspace
            resources:
              requests:
                memory: "1Gi"
                cpu: "700m"
              limits:
                memory: "3Gi"
          restartPolicy: OnFailure
          volumes:
          - name: workspace
            hostPath:
              path: /home/workspace
              type: DirectoryOrCreate
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-data-xml-check-big
  labels:
    env: develop
    tier: backend
    focus: validation
spec:
  schedule: "7/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            focus: validation
          containers:
          - name: iati-data-xml-check-big
            image: gcr.io/dataworkbench-io/iati-data-validator:0.9.7
            args:
              - xml-check-big
            volumeMounts:
            - mountPath: /workspace
              name: workspace
            resources:
              requests:
                memory: "1Gi"
                cpu: "700m"
              limits:
                memory: "3Gi"
          restartPolicy: OnFailure
          volumes:
          - name: workspace
            hostPath:
              path: /home/workspace
              type: DirectoryOrCreate
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: iati-data-xml-check
  labels:
    env: develop
    tier: backend
    focus: validation
spec:
  schedule: "7/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            focus: validation
          containers:
          - name: iati-data-xml-check
            image: gcr.io/dataworkbench-io/iati-data-validator:0.9.7
            args:
              - xml-check
            volumeMounts:
            - mountPath: /workspace
              name: workspace
            resources:
              requests:
                memory: "1Gi"
                cpu: "700m"
              limits:
                memory: "3Gi"
          restartPolicy: OnFailure
          volumes:
          - name: workspace
            hostPath:
              path: /home/workspace
              type: DirectoryOrCreate
