apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: front-end
  selector:
    app: homepage
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  # override in deploy/scaling.yaml
  replicas: 1
  template:
    metadata:
      labels:
        app: homepage
        tier: frontend
    spec:
      nodeSelector:
        node: core
      containers:
      - name: homepage
        image: gcr.io/dataworkbench-io/homepage:0.3.6
        imagePullPolicy: Always
        ports:
        - name: front-end
          containerPort: 80
        envFrom:
        - configMapRef:
          name: homepage-config
      