apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iati-data-validator-loop
  labels:
    app: iati-data-validator-loop
spec:
  template:
    metadata:
      labels:
        app: iati-data-validator-loop
        tier: backend
    spec:
      nodeSelector:
        node: preemptible
      containers:
      - name: iati-data-validator-loop
        image: gcr.io/dataworkbench-io/iati-data-validator:0.11.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"
            cpu: 300m
        env:
          - name: PROJECT_ID
            value: dataworkbench-io
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      volumes:
      - name: workspace
        emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iati-data-validator
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iati-data-validator-loop
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
