# https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataworkbench-ingress
  annotations:
    networking.gke.io/managed-certificates: web-certificate
    # If the class annotation is not specified it defaults to "gce" (external lb).
    # kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "dataworkbench-frontend-config"
spec:
  # ingressClassName: external-lb
  defaultBackend:
    service:
      name: homepage
      port:
        number: 80
  rules:
    - http:
        paths:
          # GKE ingress uses url-maps that require wildcards
          # and also a separate (duplicate) rule for URLs to a directory
          # but not ending with a '/'
        - path: /iati-feedback
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-front-end
              port:
                number: 80
        - path: /iati-feedback/*
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-front-end
              port:
                number: 80
              
        - path: /api/v1
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-api-public
              port:
                number: 80
        - path: /api/v1/*
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-api-public
              port:
                number: 80

        - path: /explorer
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-api-public
              port:
                number: 80
        - path: /explorer/*
          pathType: ImplementationSpecific
          backend:
            service:
              name: validator-api-public
              port:
                number: 80

        - path: /process
          pathType: ImplementationSpecific
          backend:
            service:
              name: iati-data-validator-webhook
              port:
                number: 80
        - path: /process/*
          pathType: ImplementationSpecific
          backend:
            service:
              name: iati-data-validator-webhook
              port:
                number: 80

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dataworkbench-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: dwb-backendconfig-longtimeout
spec:
  timeoutSec: 3600
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: web-certificate
