apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dataworkbench-ingress
  annotations:
    networking.gke.io/managed-certificates: web-certificate
spec:
  backend:
    serviceName: homepage
    servicePort: 80
  rules:
    - http:
        paths:
          # GKE ingress uses url-maps that require wildcards
          # and also a separate (duplicate) rule for URLs to a directory
          # but not ending with a '/'
        - path: /iati-feedback
          backend:
            serviceName: validator-front-end
            servicePort: 80
        - path: /iati-feedback/*
          backend:
            serviceName: validator-front-end
            servicePort: 80
        - path: /api/v1
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /api/v1/*
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /explorer
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /explorer/*
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /process
          backend:
            serviceName: iati-data-validator-webhook
            servicePort: 80
        - path: /process/*
          backend:
            serviceName: iati-data-validator-webhook
            servicePort: 80
---
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: dwb-backendconfig-longtimeout
spec:
  timeoutSec: 3600
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: web-certificate
