apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dataworkbench-ingress
  annotations:
    networking.gke.io/managed-certificates: web-certificate
spec:
  backend:
    serviceName: validator-front-end
    servicePort: 80
  rules:
    - http:
        paths:
          # GKE ingress uses url-maps that require wildcards
          # and also a separate (duplicate) rule for URLs to a directory
          # but not ending with a '/'
        - path: /api/v1
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /api/v1/*
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /explorer
          backend:
            serviceName: validator-api-public
            servicePort: 80
        - path: /explorer/*
          backend:
            serviceName: validator-api-public
            servicePort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: web-certificate
spec:
  domains:
    - example.com
