apiVersion: v1
kind: Service
metadata:
  name: validator-api
  labels:
    app: validator-api
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: api-server
  selector:
    app: validator-api
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api
  labels:
    app: validator-api
spec:
  # override in deploy/scaling.yaml
  replicas: 1
  selector:
    matchLabels:
      app: validator-api
  template:
    metadata:
      labels:
        app: validator-api
        tier: frontend
    spec:
      containers:
      - name: validator-api-app
        image: gcr.io/d4d-dataworkbench/validator-api:1.0.0
        imagePullPolicy: Always
        ports:
        - name: api-server
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: validator-api-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "200m"
        volumeMounts:
        - name: api-datasources-properties-volume
          mountPath: /app/server/datasources.local.json
          subPath: datasources.local.json
      volumes:
      - name: api-datasources-properties-volume
        configMap:
          name: api-datasources-properties
---            
apiVersion: v1
kind: Service
metadata:
  name: validator-api-public
  labels:
    app: validator-api-public
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: api-public
  selector:
    app: validator-api-public
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-api-public
  labels:
    app: validator-api-public
spec:
  # override in deploy/scaling.yaml
  replicas: 1
  selector:
    matchLabels:
      app: validator-api-public
  template:
    metadata:
      labels:
        app: validator-api-public
        tier: frontend
    spec:
      containers:
      - name: validator-api-public-app
        image: gcr.io/d4d-dataworkbench/validator-api:1.0.0
        imagePullPolicy: Always
        ports:
        - name: api-public
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: validator-api-public-config
        env:
        - name: API_TYPE
          value: "public"
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "200m"
        volumeMounts:
        - name: api-datasources-properties-volume
          mountPath: /app/server/datasources.local.json
          subPath: datasources.local.json
      volumes:
      - name: api-datasources-properties-volume
        configMap:
          name: api-datasources-properties

