
# Site settings
title: DataWorkbench cluster setup
email: rolf@drostan.org
description: Configurations for the Kubernetes cluster
brand: DataWorkbench
github: data4development/dataworkbench-cluster

defaults:
  -
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme 

remote_theme: data4development/dataworkbench-jekyll-theme
