@startuml

cloud "Google Kubernetes Cluster" {
  node "DataWorkbench Services" as dwbservices {
    component "Front-end" as frontend
    database "Mongo" as mongo
    component API

    frontend -right-> API
    API -- mongo
  }

  boundary Ingress
  Ingress -- API
  Ingress -- frontend

  node "Validator Engine" as validatorengine {
    folder Snapshot
    folder Workspace
    control "IATI Validator" as validator
    control "IATI Refresher" as refresher
    control "Cleanup"
    validator -- Workspace
    refresher -- Snapshot
    refresher -- Workspace
    Cleanup -- Workspace
  }

  rectangle "Google Cloud" {
    storage "File storage" as storage
    storage "Persistent disks" as pd
    storage "Code repository" as repositories
    queue "Message queue" as pubsub
  }

  validatorengine --> API
  mongo --> pd
  refresher --> pubsub
  API --> storage
  API --> pubsub
  Workspace --> storage
  Snapshot --> repositories
}


actor User
User --> Ingress

interface "IATI Registry" as iati
iati <-- refresher

@enduml
